// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.36.2
// source: collector/v1/collector.proto

package collectorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_Register
	//	*AgentMessage_Heartbeat
	//	*AgentMessage_Metrics
	//	*AgentMessage_Event
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_collector_v1_collector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_collector_v1_collector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_collector_v1_collector_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetRegister() *Register {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentMessage) GetMetrics() *MetricBatch {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Metrics); ok {
			return x.Metrics
		}
	}
	return nil
}

func (x *AgentMessage) GetEvent() *AgentEvent {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Event); ok {
			return x.Event
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_Register struct {
	Register *Register `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type AgentMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type AgentMessage_Metrics struct {
	Metrics *MetricBatch `protobuf:"bytes,3,opt,name=metrics,proto3,oneof"`
}

type AgentMessage_Event struct {
	Event *AgentEvent `protobuf:"bytes,4,opt,name=event,proto3,oneof"`
}

func (*AgentMessage_Register) isAgentMessage_Payload() {}

func (*AgentMessage_Heartbeat) isAgentMessage_Payload() {}

func (*AgentMessage_Metrics) isAgentMessage_Payload() {}

func (*AgentMessage_Event) isAgentMessage_Payload() {}

type Register struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AgentId         string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	BootId          string                 `protobuf:"bytes,2,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`
	Hostname        string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	IpAddress       string                 `protobuf:"bytes,4,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Os              string                 `protobuf:"bytes,5,opt,name=os,proto3" json:"os,omitempty"`
	Architecture    string                 `protobuf:"bytes,6,opt,name=architecture,proto3" json:"architecture,omitempty"`
	AgentVersion    string                 `protobuf:"bytes,7,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	TelegrafVersion string                 `protobuf:"bytes,8,opt,name=telegraf_version,json=telegrafVersion,proto3" json:"telegraf_version,omitempty"`
	ConfigVersion   string                 `protobuf:"bytes,9,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	Labels          map[string]string      `protobuf:"bytes,10,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Register) Reset() {
	*x = Register{}
	mi := &file_collector_v1_collector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Register) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Register) ProtoMessage() {}

func (x *Register) ProtoReflect() protoreflect.Message {
	mi := &file_collector_v1_collector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Register.ProtoReflect.Descriptor instead.
func (*Register) Descriptor() ([]byte, []int) {
	return file_collector_v1_collector_proto_rawDescGZIP(), []int{1}
}

func (x *Register) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Register) GetBootId() string {
	if x != nil {
		return x.BootId
	}
	return ""
}

func (x *Register) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Register) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *Register) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Register) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *Register) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *Register) GetTelegrafVersion() string {
	if x != nil {
		return x.TelegrafVersion
	}
	return ""
}

func (x *Register) GetConfigVersion() string {
	if x != nil {
		return x.ConfigVersion
	}
	return ""
}

func (x *Register) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type Heartbeat struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	AgentId                    string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	BootId                     string                 `protobuf:"bytes,2,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`
	Sequence                   uint64                 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	SentAtUnixNano             int64                  `protobuf:"varint,4,opt,name=sent_at_unix_nano,json=sentAtUnixNano,proto3" json:"sent_at_unix_nano,omitempty"`
	TelegrafState              string                 `protobuf:"bytes,5,opt,name=telegraf_state,json=telegrafState,proto3" json:"telegraf_state,omitempty"`
	TelegrafVersion            string                 `protobuf:"bytes,6,opt,name=telegraf_version,json=telegrafVersion,proto3" json:"telegraf_version,omitempty"`
	TelegrafLastMetricUnixNano int64                  `protobuf:"varint,7,opt,name=telegraf_last_metric_unix_nano,json=telegrafLastMetricUnixNano,proto3" json:"telegraf_last_metric_unix_nano,omitempty"`
	QueueBytes                 uint64                 `protobuf:"varint,8,opt,name=queue_bytes,json=queueBytes,proto3" json:"queue_bytes,omitempty"`
	DroppedMetricBatches       uint64                 `protobuf:"varint,9,opt,name=dropped_metric_batches,json=droppedMetricBatches,proto3" json:"dropped_metric_batches,omitempty"`
	TelegrafRunning            bool                   `protobuf:"varint,10,opt,name=telegraf_running,json=telegrafRunning,proto3" json:"telegraf_running,omitempty"`
	TelegrafPid                uint32                 `protobuf:"varint,11,opt,name=telegraf_pid,json=telegrafPid,proto3" json:"telegraf_pid,omitempty"`
	AgentStartedAtUnixNano     int64                  `protobuf:"varint,12,opt,name=agent_started_at_unix_nano,json=agentStartedAtUnixNano,proto3" json:"agent_started_at_unix_nano,omitempty"`
	AgentMemoryBytes           uint64                 `protobuf:"varint,13,opt,name=agent_memory_bytes,json=agentMemoryBytes,proto3" json:"agent_memory_bytes,omitempty"`
	AgentGoroutines            uint64                 `protobuf:"varint,14,opt,name=agent_goroutines,json=agentGoroutines,proto3" json:"agent_goroutines,omitempty"`
	QueueCapacityBytes         uint64                 `protobuf:"varint,15,opt,name=queue_capacity_bytes,json=queueCapacityBytes,proto3" json:"queue_capacity_bytes,omitempty"`
	QueueUsagePercent          float64                `protobuf:"fixed64,16,opt,name=queue_usage_percent,json=queueUsagePercent,proto3" json:"queue_usage_percent,omitempty"`
	QueueAlertLevel            string                 `protobuf:"bytes,17,opt,name=queue_alert_level,json=queueAlertLevel,proto3" json:"queue_alert_level,omitempty"`
	OsVersion                  string                 `protobuf:"bytes,18,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	SystemTimeUnixNano         int64                  `protobuf:"varint,19,opt,name=system_time_unix_nano,json=systemTimeUnixNano,proto3" json:"system_time_unix_nano,omitempty"`
	MemoryTotalBytes           uint64                 `protobuf:"varint,20,opt,name=memory_total_bytes,json=memoryTotalBytes,proto3" json:"memory_total_bytes,omitempty"`
	MemoryUsedBytes            uint64                 `protobuf:"varint,21,opt,name=memory_used_bytes,json=memoryUsedBytes,proto3" json:"memory_used_bytes,omitempty"`
	ProcessCount               uint64                 `protobuf:"varint,22,opt,name=process_count,json=processCount,proto3" json:"process_count,omitempty"`
	ListeningPortCount         uint64                 `protobuf:"varint,23,opt,name=listening_port_count,json=listeningPortCount,proto3" json:"listening_port_count,omitempty"`
	Load1                      float64                `protobuf:"fixed64,24,opt,name=load1,proto3" json:"load1,omitempty"`
	SystemUptimeSeconds        uint64                 `protobuf:"varint,25,opt,name=system_uptime_seconds,json=systemUptimeSeconds,proto3" json:"system_uptime_seconds,omitempty"`
	CpuModel                   string                 `protobuf:"bytes,26,opt,name=cpu_model,json=cpuModel,proto3" json:"cpu_model,omitempty"`
	PhysicalCpuCores           uint64                 `protobuf:"varint,27,opt,name=physical_cpu_cores,json=physicalCpuCores,proto3" json:"physical_cpu_cores,omitempty"`
	LogicalCpuCores            uint64                 `protobuf:"varint,28,opt,name=logical_cpu_cores,json=logicalCpuCores,proto3" json:"logical_cpu_cores,omitempty"`
	HardwareTemperatureC       float64                `protobuf:"fixed64,29,opt,name=hardware_temperature_c,json=hardwareTemperatureC,proto3" json:"hardware_temperature_c,omitempty"`
	Processes                  []*ProcessInfo         `protobuf:"bytes,30,rep,name=processes,proto3" json:"processes,omitempty"`
	Temperatures               []*TemperatureReading  `protobuf:"bytes,31,rep,name=temperatures,proto3" json:"temperatures,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_collector_v1_collector_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_collector_v1_collector_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_collector_v1_collector_proto_rawDescGZIP(), []int{2}
}

func (x *Heartbeat) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Heartbeat) GetBootId() string {
	if x != nil {
		return x.BootId
	}
	return ""
}

func (x *Heartbeat) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Heartbeat) GetSentAtUnixNano() int64 {
	if x != nil {
		return x.SentAtUnixNano
	}
	return 0
}

func (x *Heartbeat) GetTelegrafState() string {
	if x != nil {
		return x.TelegrafState
	}
	return ""
}

func (x *Heartbeat) GetTelegrafVersion() string {
	if x != nil {
		return x.TelegrafVersion
	}
	return ""
}

func (x *Heartbeat) GetTelegrafLastMetricUnixNano() int64 {
	if x != nil {
		return x.TelegrafLastMetricUnixNano
	}
	return 0
}

func (x *Heartbeat) GetQueueBytes() uint64 {
	if x != nil {
		return x.QueueBytes
	}
	return 0
}

func (x *Heartbeat) GetDroppedMetricBatches() uint64 {
	if x != nil {
		return x.DroppedMetricBatches
	}
	return 0
}

func (x *Heartbeat) GetTelegrafRunning() bool {
	if x != nil {
		return x.TelegrafRunning
	}
	return false
}

func (x *Heartbeat) GetTelegrafPid() uint32 {
	if x != nil {
		return x.TelegrafPid
	}
	return 0
}

func (x *Heartbeat) GetAgentStartedAtUnixNano() int64 {
	if x != nil {
		return x.AgentStartedAtUnixNano
	}
	return 0
}

func (x *Heartbeat) GetAgentMemoryBytes() uint64 {
	if x != nil {
		return x.AgentMemoryBytes
	}
	return 0
}

func (x *Heartbeat) GetAgentGoroutines() uint64 {
	if x != nil {
		return x.AgentGoroutines
	}
	return 0
}

func (x *Heartbeat) GetQueueCapacityBytes() uint64 {
	if x != nil {
		return x.QueueCapacityBytes
	}
	return 0
}

func (x *Heartbeat) GetQueueUsagePercent() float64 {
	if x != nil {
		return x.QueueUsagePercent
	}
	return 0
}

func (x *Heartbeat) GetQueueAlertLevel() string {
	if x != nil {
		return x.QueueAlertLevel
	}
	return ""
}

func (x *Heartbeat) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *Heartbeat) GetSystemTimeUnixNano() int64 {
	if x != nil {
		return x.SystemTimeUnixNano
	}
	return 0
}

func (x *Heartbeat) GetMemoryTotalBytes() uint64 {
	if x != nil {
		return x.MemoryTotalBytes
	}
	return 0
}

func (x *Heartbeat) GetMemoryUsedBytes() uint64 {
	if x != nil {
		return x.MemoryUsedBytes
	}
	return 0
}

func (x *Heartbeat) GetProcessCount() uint64 {
	if x != nil {
		return x.ProcessCount
	}
	return 0
}

func (x *Heartbeat) GetListeningPortCount() uint64 {
	if x != nil {
		return x.ListeningPortCount
	}
	return 0
}

func (x *Heartbeat) GetLoad1() float64 {
	if x != nil {
		return x.Load1
	}
	return 0
}

func (x *Heartbeat) GetSystemUptimeSeconds() uint64 {
	if x != nil {
		return x.SystemUptimeSeconds
	}
	return 0
}

func (x *Heartbeat) GetCpuModel() string {
	if x != nil {
		return x.CpuModel
	}
	return ""
}

func (x *Heartbeat) GetPhysicalCpuCores() uint64 {
	if x != nil {
		return x.PhysicalCpuCores
	}
	return 0
}

func (x *Heartbeat) GetLogicalCpuCores() uint64 {
	if x != nil {
		return x.LogicalCpuCores
	}
	return 0
}

func (x *Heartbeat) GetHardwareTemperatureC() float64 {
	if x != nil {
		return x.HardwareTemperatureC
	}
	return 0
}

func (x *Heartbeat) GetProcesses() []*ProcessInfo {
	if x != nil {
		return x.Processes
	}
	return nil
}

func (x *Heartbeat) GetTemperatures() []*TemperatureReading {
	if x != nil {
		return x.Temperatures
	}
	return nil
}

type ProcessInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	MemoryBytes   uint64                 `protobuf:"varint,3,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessInfo) Reset() {
	*x = ProcessInfo{}
	mi := &file_collector_v1_collector_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessInfo) ProtoMessage() {}

func (x *ProcessInfo) ProtoReflect() protoreflect.Message {
	mi := &file_collector_v1_collector_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessInfo.ProtoReflect.Descriptor instead.
func (*ProcessInfo) Descriptor() ([]byte, []int) {
	return file_collector_v1_collector_proto_rawDescGZIP(), []int{3}
}

func (x *ProcessInfo) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProcessInfo) GetMemoryBytes() uint64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

type TemperatureReading struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Celsius       float64                `protobuf:"fixed64,2,opt,name=celsius,proto3" json:"celsius,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemperatureReading) Reset() {
	*x = TemperatureReading{}
	mi := &file_collector_v1_collector_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemperatureReading) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemperatureReading) ProtoMessage() {}

func (x *TemperatureReading) ProtoReflect() protoreflect.Message {
	mi := &file_collector_v1_collector_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemperatureReading.ProtoReflect.Descriptor instead.
func (*TemperatureReading) Descriptor() ([]byte, []int) {
	return file_collector_v1_collector_proto_rawDescGZIP(), []int{4}
}

func (x *TemperatureReading) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TemperatureReading) GetCelsius() float64 {
	if x != nil {
		return x.Celsius
	}
	return 0
}

type MetricBatch struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AgentId             string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	BootId              string                 `protobuf:"bytes,2,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`
	Sequence            uint64                 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	CollectedAtUnixNano int64                  `protobuf:"varint,4,opt,name=collected_at_unix_nano,json=collectedAtUnixNano,proto3" json:"collected_at_unix_nano,omitempty"`
	GzipLineProtocol    []byte                 `protobuf:"bytes,5,opt,name=gzip_line_protocol,json=gzipLineProtocol,proto3" json:"gzip_line_protocol,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MetricBatch) Reset() {
	*x = MetricBatch{}
	mi := &file_collector_v1_collector_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricBatch) ProtoMessage() {}

func (x *MetricBatch) ProtoReflect() protoreflect.Message {
	mi := &file_collector_v1_collector_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricBatch.ProtoReflect.Descriptor instead.
func (*MetricBatch) Descriptor() ([]byte, []int) {
	return file_collector_v1_collector_proto_rawDescGZIP(), []int{5}
}

func (x *MetricBatch) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *MetricBatch) GetBootId() string {
	if x != nil {
		return x.BootId
	}
	return ""
}

func (x *MetricBatch) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *MetricBatch) GetCollectedAtUnixNano() int64 {
	if x != nil {
		return x.CollectedAtUnixNano
	}
	return 0
}

func (x *MetricBatch) GetGzipLineProtocol() []byte {
	if x != nil {
		return x.GzipLineProtocol
	}
	return nil
}

type AgentEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	BootId        string                 `protobuf:"bytes,2,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	DetailsJson   string                 `protobuf:"bytes,4,opt,name=details_json,json=detailsJson,proto3" json:"details_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentEvent) Reset() {
	*x = AgentEvent{}
	mi := &file_collector_v1_collector_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentEvent) ProtoMessage() {}

func (x *AgentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_collector_v1_collector_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentEvent.ProtoReflect.Descriptor instead.
func (*AgentEvent) Descriptor() ([]byte, []int) {
	return file_collector_v1_collector_proto_rawDescGZIP(), []int{6}
}

func (x *AgentEvent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentEvent) GetBootId() string {
	if x != nil {
		return x.BootId
	}
	return ""
}

func (x *AgentEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *AgentEvent) GetDetailsJson() string {
	if x != nil {
		return x.DetailsJson
	}
	return ""
}

type ServerMessage struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	ConfigVersion            string                 `protobuf:"bytes,1,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	BacklogMaxBytesPerSecond uint64                 `protobuf:"varint,2,opt,name=backlog_max_bytes_per_second,json=backlogMaxBytesPerSecond,proto3" json:"backlog_max_bytes_per_second,omitempty"`
	BacklogMaxBatches        uint32                 `protobuf:"varint,3,opt,name=backlog_max_batches,json=backlogMaxBatches,proto3" json:"backlog_max_batches,omitempty"`
	BacklogMaxParallel       uint64                 `protobuf:"varint,4,opt,name=backlog_max_parallel,json=backlogMaxParallel,proto3" json:"backlog_max_parallel,omitempty"`
	Command                  string                 `protobuf:"bytes,5,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_collector_v1_collector_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_collector_v1_collector_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_collector_v1_collector_proto_rawDescGZIP(), []int{7}
}

func (x *ServerMessage) GetConfigVersion() string {
	if x != nil {
		return x.ConfigVersion
	}
	return ""
}

func (x *ServerMessage) GetBacklogMaxBytesPerSecond() uint64 {
	if x != nil {
		return x.BacklogMaxBytesPerSecond
	}
	return 0
}

func (x *ServerMessage) GetBacklogMaxBatches() uint32 {
	if x != nil {
		return x.BacklogMaxBatches
	}
	return 0
}

func (x *ServerMessage) GetBacklogMaxParallel() uint64 {
	if x != nil {
		return x.BacklogMaxParallel
	}
	return 0
}

func (x *ServerMessage) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

var File_collector_v1_collector_proto protoreflect.FileDescriptor

const file_collector_v1_collector_proto_rawDesc = "" +
	"\n" +
	"\x1ccollector/v1/collector.proto\x12\x14monitor.collector.v1\"\x91\x02\n" +
	"\fAgentMessage\x12<\n" +
	"\bregister\x18\x01 \x01(\v2\x1e.monitor.collector.v1.RegisterH\x00R\bregister\x12?\n" +
	"\theartbeat\x18\x02 \x01(\v2\x1f.monitor.collector.v1.HeartbeatH\x00R\theartbeat\x12=\n" +
	"\ametrics\x18\x03 \x01(\v2!.monitor.collector.v1.MetricBatchH\x00R\ametrics\x128\n" +
	"\x05event\x18\x04 \x01(\v2 .monitor.collector.v1.AgentEventH\x00R\x05eventB\t\n" +
	"\apayload\"\xa3\x03\n" +
	"\bRegister\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x17\n" +
	"\aboot_id\x18\x02 \x01(\tR\x06bootId\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x04 \x01(\tR\tipAddress\x12\x0e\n" +
	"\x02os\x18\x05 \x01(\tR\x02os\x12\"\n" +
	"\farchitecture\x18\x06 \x01(\tR\farchitecture\x12#\n" +
	"\ragent_version\x18\a \x01(\tR\fagentVersion\x12)\n" +
	"\x10telegraf_version\x18\b \x01(\tR\x0ftelegrafVersion\x12%\n" +
	"\x0econfig_version\x18\t \x01(\tR\rconfigVersion\x12B\n" +
	"\x06labels\x18\n" +
	" \x03(\v2*.monitor.collector.v1.Register.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xed\n" +
	"\n" +
	"\tHeartbeat\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x17\n" +
	"\aboot_id\x18\x02 \x01(\tR\x06bootId\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x04R\bsequence\x12)\n" +
	"\x11sent_at_unix_nano\x18\x04 \x01(\x03R\x0esentAtUnixNano\x12%\n" +
	"\x0etelegraf_state\x18\x05 \x01(\tR\rtelegrafState\x12)\n" +
	"\x10telegraf_version\x18\x06 \x01(\tR\x0ftelegrafVersion\x12B\n" +
	"\x1etelegraf_last_metric_unix_nano\x18\a \x01(\x03R\x1atelegrafLastMetricUnixNano\x12\x1f\n" +
	"\vqueue_bytes\x18\b \x01(\x04R\n" +
	"queueBytes\x124\n" +
	"\x16dropped_metric_batches\x18\t \x01(\x04R\x14droppedMetricBatches\x12)\n" +
	"\x10telegraf_running\x18\n" +
	" \x01(\bR\x0ftelegrafRunning\x12!\n" +
	"\ftelegraf_pid\x18\v \x01(\rR\vtelegrafPid\x12:\n" +
	"\x1aagent_started_at_unix_nano\x18\f \x01(\x03R\x16agentStartedAtUnixNano\x12,\n" +
	"\x12agent_memory_bytes\x18\r \x01(\x04R\x10agentMemoryBytes\x12)\n" +
	"\x10agent_goroutines\x18\x0e \x01(\x04R\x0fagentGoroutines\x120\n" +
	"\x14queue_capacity_bytes\x18\x0f \x01(\x04R\x12queueCapacityBytes\x12.\n" +
	"\x13queue_usage_percent\x18\x10 \x01(\x01R\x11queueUsagePercent\x12*\n" +
	"\x11queue_alert_level\x18\x11 \x01(\tR\x0fqueueAlertLevel\x12\x1d\n" +
	"\n" +
	"os_version\x18\x12 \x01(\tR\tosVersion\x121\n" +
	"\x15system_time_unix_nano\x18\x13 \x01(\x03R\x12systemTimeUnixNano\x12,\n" +
	"\x12memory_total_bytes\x18\x14 \x01(\x04R\x10memoryTotalBytes\x12*\n" +
	"\x11memory_used_bytes\x18\x15 \x01(\x04R\x0fmemoryUsedBytes\x12#\n" +
	"\rprocess_count\x18\x16 \x01(\x04R\fprocessCount\x120\n" +
	"\x14listening_port_count\x18\x17 \x01(\x04R\x12listeningPortCount\x12\x14\n" +
	"\x05load1\x18\x18 \x01(\x01R\x05load1\x122\n" +
	"\x15system_uptime_seconds\x18\x19 \x01(\x04R\x13systemUptimeSeconds\x12\x1b\n" +
	"\tcpu_model\x18\x1a \x01(\tR\bcpuModel\x12,\n" +
	"\x12physical_cpu_cores\x18\x1b \x01(\x04R\x10physicalCpuCores\x12*\n" +
	"\x11logical_cpu_cores\x18\x1c \x01(\x04R\x0flogicalCpuCores\x124\n" +
	"\x16hardware_temperature_c\x18\x1d \x01(\x01R\x14hardwareTemperatureC\x12?\n" +
	"\tprocesses\x18\x1e \x03(\v2!.monitor.collector.v1.ProcessInfoR\tprocesses\x12L\n" +
	"\ftemperatures\x18\x1f \x03(\v2(.monitor.collector.v1.TemperatureReadingR\ftemperatures\"V\n" +
	"\vProcessInfo\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fmemory_bytes\x18\x03 \x01(\x04R\vmemoryBytes\"B\n" +
	"\x12TemperatureReading\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acelsius\x18\x02 \x01(\x01R\acelsius\"\xc0\x01\n" +
	"\vMetricBatch\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x17\n" +
	"\aboot_id\x18\x02 \x01(\tR\x06bootId\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x04R\bsequence\x123\n" +
	"\x16collected_at_unix_nano\x18\x04 \x01(\x03R\x13collectedAtUnixNano\x12,\n" +
	"\x12gzip_line_protocol\x18\x05 \x01(\fR\x10gzipLineProtocol\"\x82\x01\n" +
	"\n" +
	"AgentEvent\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x17\n" +
	"\aboot_id\x18\x02 \x01(\tR\x06bootId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12!\n" +
	"\fdetails_json\x18\x04 \x01(\tR\vdetailsJson\"\xf2\x01\n" +
	"\rServerMessage\x12%\n" +
	"\x0econfig_version\x18\x01 \x01(\tR\rconfigVersion\x12>\n" +
	"\x1cbacklog_max_bytes_per_second\x18\x02 \x01(\x04R\x18backlogMaxBytesPerSecond\x12.\n" +
	"\x13backlog_max_batches\x18\x03 \x01(\rR\x11backlogMaxBatches\x120\n" +
	"\x14backlog_max_parallel\x18\x04 \x01(\x04R\x12backlogMaxParallel\x12\x18\n" +
	"\acommand\x18\x05 \x01(\tR\acommand2j\n" +
	"\x10CollectorService\x12V\n" +
	"\aConnect\x12\".monitor.collector.v1.AgentMessage\x1a#.monitor.collector.v1.ServerMessage(\x010\x01B3Z1monitor-server/api/proto/collector/v1;collectorv1b\x06proto3"

var (
	file_collector_v1_collector_proto_rawDescOnce sync.Once
	file_collector_v1_collector_proto_rawDescData []byte
)

func file_collector_v1_collector_proto_rawDescGZIP() []byte {
	file_collector_v1_collector_proto_rawDescOnce.Do(func() {
		file_collector_v1_collector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_collector_v1_collector_proto_rawDesc), len(file_collector_v1_collector_proto_rawDesc)))
	})
	return file_collector_v1_collector_proto_rawDescData
}

var file_collector_v1_collector_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_collector_v1_collector_proto_goTypes = []any{
	(*AgentMessage)(nil),       // 0: monitor.collector.v1.AgentMessage
	(*Register)(nil),           // 1: monitor.collector.v1.Register
	(*Heartbeat)(nil),          // 2: monitor.collector.v1.Heartbeat
	(*ProcessInfo)(nil),        // 3: monitor.collector.v1.ProcessInfo
	(*TemperatureReading)(nil), // 4: monitor.collector.v1.TemperatureReading
	(*MetricBatch)(nil),        // 5: monitor.collector.v1.MetricBatch
	(*AgentEvent)(nil),         // 6: monitor.collector.v1.AgentEvent
	(*ServerMessage)(nil),      // 7: monitor.collector.v1.ServerMessage
	nil,                        // 8: monitor.collector.v1.Register.LabelsEntry
}
var file_collector_v1_collector_proto_depIdxs = []int32{
	1, // 0: monitor.collector.v1.AgentMessage.register:type_name -> monitor.collector.v1.Register
	2, // 1: monitor.collector.v1.AgentMessage.heartbeat:type_name -> monitor.collector.v1.Heartbeat
	5, // 2: monitor.collector.v1.AgentMessage.metrics:type_name -> monitor.collector.v1.MetricBatch
	6, // 3: monitor.collector.v1.AgentMessage.event:type_name -> monitor.collector.v1.AgentEvent
	8, // 4: monitor.collector.v1.Register.labels:type_name -> monitor.collector.v1.Register.LabelsEntry
	3, // 5: monitor.collector.v1.Heartbeat.processes:type_name -> monitor.collector.v1.ProcessInfo
	4, // 6: monitor.collector.v1.Heartbeat.temperatures:type_name -> monitor.collector.v1.TemperatureReading
	0, // 7: monitor.collector.v1.CollectorService.Connect:input_type -> monitor.collector.v1.AgentMessage
	7, // 8: monitor.collector.v1.CollectorService.Connect:output_type -> monitor.collector.v1.ServerMessage
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_collector_v1_collector_proto_init() }
func file_collector_v1_collector_proto_init() {
	if File_collector_v1_collector_proto != nil {
		return
	}
	file_collector_v1_collector_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentMessage_Register)(nil),
		(*AgentMessage_Heartbeat)(nil),
		(*AgentMessage_Metrics)(nil),
		(*AgentMessage_Event)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_collector_v1_collector_proto_rawDesc), len(file_collector_v1_collector_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_collector_v1_collector_proto_goTypes,
		DependencyIndexes: file_collector_v1_collector_proto_depIdxs,
		MessageInfos:      file_collector_v1_collector_proto_msgTypes,
	}.Build()
	File_collector_v1_collector_proto = out.File
	file_collector_v1_collector_proto_goTypes = nil
	file_collector_v1_collector_proto_depIdxs = nil
}
